service: redemet-crawler

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:HeadObject
        - s3:ListBucket
      Resource: 
        - "arn:aws:s3:::${env:BUCKET_NAME}"
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"


functions:
  redemet-crawler:
    handler: handler.redemet_crawler
    memorySize: 128
    timeout: 270
    events:
      # - schedule: rate(5 minutes)

  latest-images:
    handler: handler.check_redemet
    events:
      - http: 
          path: /images
          method: get
          cors: false

resources:
 Resources:
   Bucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${env:BUCKET_NAME}