service: redemet-crawler

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
  SNS_ERROR_PATH: ${env:DEFAULT_REGION}:${env:AWS_ID}:${env:SNS_ERROR_TOPIC}

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  timeout: 270

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObjectAcl
        - s3:PutObject
        - s3:GetObject
        - s3:HeadObject
        - s3:ListBucket
      Resource: 
        - "arn:aws:s3:::${env:BUCKET_NAME}"
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"


functions:
  get-redemet-api:
    handler: src/handler.api_handler
    memorySize: 128
    timeout: 270
    events:
      - schedule: rate(5 minutes)
    reservedConcurrency: 1
    onError: arn:aws:sns:${self:custom.SNS_ERROR_PATH}

